_portfolio:
    resource: "@StfalconPortfolioBundle/Controller"
    type:     annotation
    prefix:   /{_locale}/portfolio
    requirements:
        _locale: ru|uk|en
    defaults:
        _locale: %locale%